# Generated by Django 5.2.7 on 2025-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_mob', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('father_mob', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mob', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=12)),
                ('blood_group', models.CharField(max_length=5)),
                ('partner_choice', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('passport_photo', models.TextField(blank=True)),
                ('full_photo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
