# Generated by Django 5.2.7 on 2025-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_age_registration_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='birth_time',
            new_name='birthTime',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='job_type',
            new_name='jobType',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='skin_colour',
            new_name='skinColour',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='joint_income',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='personal_income',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='prof_address',
        ),
        migrations.AddField(
            model_name='registration',
            name='birthPlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='jointIncome',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='personalIncome',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='profAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='registration',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='father_mob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='father_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='house',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mother_mob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='partner_choice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='your_mob',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='your_name',
            field=models.CharField(max_length=100),
        ),
    ]
