# Generated by Django 5.2.7 on 2025-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_aakay_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='married',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
