# Generated by Django 5.2.7 on 2025-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registration_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
