# Generated by Django 5.2.7 on 2025-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
