# Generated by Django 5.2.7 on 2025-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
