# Generated by Django 5.2.7 on 2025-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_registration_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='drinks',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='nonVeg',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smokes',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='widow',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
