# Generated by Django 5.2.7 on 2025-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_registration_drinks_registration_nonveg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='business',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='grandparents',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='inlaws',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='profAddressStep3',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='profName',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='siblings',
        ),
        migrations.AddField(
            model_name='registration',
            name='BrotherBusiness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='BrotherBusinessAd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherBusiness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherBusinessAd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='OwnBusiness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='OwnBusinessAd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='brother',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='grandfather',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='grandmother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='sister',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aakay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='drinks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='drinksAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='married',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nonVeg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nonVegAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='nukha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='smokes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='smokesAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='widow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='widowAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
