# Generated by Django 5.2.7 on 2025-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_registration_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='OwnBusiness',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='OwnBusinessAd',
        ),
        migrations.AddField(
            model_name='registration',
            name='BrotherPos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherPos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
