# Generated by Django 5.2.7 on 2025-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_registration_ownbusiness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='married',
        ),
        migrations.AddField(
            model_name='registration',
            name='marriedb',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='marrieds',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
