# Generated by Django 5.2.7 on 2025-10-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_remove_registration_married_registration_marriedb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='BrotherBusiness',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='BrotherBusinessAd',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='BrotherPos',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='FatherBusiness',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='FatherBusinessAd',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='FatherPos',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='aakay',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='drinksAccept',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='father',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='grandfather',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='grandmother',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='members',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='nonVegAccept',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='nukha',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='otherInfo',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='sindh',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='smokesAccept',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='widowAccept',
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
