# Generated by Django 5.2.7 on 2025-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_remove_registration_brotherbusiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='BrotherBusiness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='BrotherBusinessAd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='BrotherPos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherBusiness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherBusinessAd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='FatherPos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='aakay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='drinksAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='grandfather',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='grandmother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='nonVegAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='nukha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='otherInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='sindh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='smokesAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='widowAccept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
