"""
Django settings for website project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

# -------------------------------
# BASE DIRECTORY
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------
# SECURITY
# -------------------------------
SECRET_KEY = 'django-insecure-!e*7asa9lcm&dc&gia%qg$d6%khcz -f1k(8fe=$ax%a^gdrf4n'
DEBUG = False  # Must be False for Render deployment

ALLOWED_HOSTS = [
    'sindhiMaitryuen.onrender.com',
    'www.sindhiMaitryuen.com',
    'sindhiMaitryuen.com',
    '.onrender.com',
    '127.0.0.1',
    'localhost',
]


# -------------------------------
# OTP
# -------------------------------
FAST2SMS_API_KEY = "Mf8opzbtGTFrQNHSBw9c3Ina6ULd0Cl5VxAYvZiyjOJe7s1PXK6UNDKGuS375q0FmeM4Wst1Xahl2R9v"

FAST2SMS_SENDER_ID = "SMBSMJ"     # from Jio/FAST2SMS
FAST2SMS_MESSAGE_ID = "204238"    # THIS is the Fast2SMS Message ID (NOT DLT ID)

OTP_TTL_SECONDS = 300
OTP_RESEND_COOLDOWN = 45

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "sindhimate-cache"
    }
}

# -------------------------------
# APPLICATIONS
# -------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
]


# -------------------------------
# MIDDLEWARE
# -------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Must come right after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -------------------------------
# URLS / WSGI
# -------------------------------
ROOT_URLCONF = 'website.urls'
WSGI_APPLICATION = 'website.wsgi.application'


# -------------------------------
# TEMPLATES
# -------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -------------------------------
# DATABASE
# -------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -------------------------------
# PASSWORD VALIDATION
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -------------------------------
# INTERNATIONALIZATION
# -------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------------
# STATIC FILES (CSS, JS, IMAGES)
# -------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # where your app static/ folder is
STATIC_ROOT = BASE_DIR / 'staticfiles'    # where collectstatic will dump files

# Enable WhiteNoise compressed static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# -------------------------------
# UPLOAD SIZE (OPTIONAL)
# -------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB


# -------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
